### ISSUE TITLE
Can't save plots as pdfs

### ISSUE THREAD

**Issue by elliottbiondo** [Pshriwise/dag_slicer#2]
I have never seen this before with matplotlib. I get the same error when I modify things on the dag_slicer side and try to save with `plt.savefig()`.

![image](https://cloud.githubusercontent.com/assets/1749283/10829535/834489c4-7e48-11e5-9049-81450d0d076d.png)

**Comment by Pshriwise** [comment]
Fixed in aff015c5105c011c6f8428b26baf2c9ed262e817. 

Was a matter of ensuring the colors were not numpy arrays but lists instead. Problem was identified by looking at Matplotlib's pdf backend [here](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_pdf.py).
